// Auto-generated by export-category-seed.js on 2026-03-02
// To regenerate: node backend/export-category-seed.js

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Skip if categories already exist in this DB
    const { count } = await knex('transaction_categories').count('* as count').first();
    if (parseInt(count) > 0) return;

    await knex('transaction_categories').insert([
        { name: "Membership fees", description: "", color: "#0077be" },
        { name: "Banking fees", description: "", color: "#3b7e3a" },
        { name: "PRS income", description: "", color: "#ffae00" },
        { name: "Pool payments", description: "", color: "#1f00bd" },
        { name: "Trainer payments", description: "", color: "#bd0081" },
        { name: "Digital services", description: "", color: "#eeff00" },
        { name: "Bootcamp", description: "", color: "#ff0000" },
        { name: "Swimming association fees", description: "", color: "#c28e00" }
    ]);

    const cats = await knex('transaction_categories').select('id', 'name');
    const catMap = Object.fromEntries(cats.map(c => [c.name, c.id]));

    await knex('transaction_category_rules').insert([
        { category_id: catMap["Membership fees"], field: "amount", operator: "equals", value: "1350", priority: 0 },
        { category_id: catMap["Membership fees"], field: "variable_symbol", operator: "regex", value: "^1\\d{3}$", priority: 0 },
        { category_id: catMap["Banking fees"], field: "transaction_type", operator: "contains", value: "Cena za služby", priority: 0 },
        { category_id: catMap["Banking fees"], field: "transaction_type", operator: "contains", value: "Cena za tuzemskou", priority: 0 },
        { category_id: catMap["Banking fees"], field: "transaction_type", operator: "contains", value: "Cena za zahraniční", priority: 0 },
        { category_id: catMap["PRS income"], field: "transaction_type", operator: "contains", value: "SEPA", priority: 0 },
        { category_id: catMap["Pool payments"], field: "counterparty_name", operator: "contains", value: "TRADE CENTRE", priority: 0 },
        { category_id: catMap["Trainer payments"], field: "message_for_recipient", operator: "contains", value: "trenér", priority: 0 },
        { category_id: catMap["Trainer payments"], field: "counterparty_name", operator: "contains", value: "trenér", priority: 0 },
        { category_id: catMap["Trainer payments"], field: "message_for_recipient", operator: "contains", value: "trenink", priority: 0 },
        { category_id: catMap["Digital services"], field: "counterparty_name", operator: "contains", value: "WEDOS", priority: 0 },
        { category_id: catMap["Digital services"], field: "counterparty_name", operator: "contains", value: "ABRA", priority: 0 },
        { category_id: catMap["Swimming association fees"], field: "counterparty_name", operator: "contains", value: "svaz", priority: 0 }
    ]);
};
